public enum TypeOfTool {
    NOTHING,
    DECORATION_TOOL_SET,
    ROAD_TOOL_SET,
    ELECTRICITY_TOOL_SET,
    PLANTING_TOOL_SET,
    BUILDING_TOOL_SET,
    ROCKET_TOOL_SET,
    ROCKET_INSTALLING_SET

}
