public enum TypeOfWork {
    ROAD_BUILDING,
    ELECTRICITY_BUILDING,
    FLOWERS_PLANTING,
    INDOOR_DECORATION,
    PAINTING_WORKS,
    NOTHING,
    RELAXING,
    HOUSE_BUILDING,
    ROCKET_DETAIL_BUILDING,
    ROCKET_PARTS_BUILDING,
    ROCKET_LOWER_INSTALLING,
    ROCKET_UPPER_INSTALLING
}
